### ISSUE TITLE
Generic Thank You Page

### ISSUE THREAD

**Issue by interstellarnick** [interstellarnick/interstellar-website#14]
A page, interstellardigital.com/thank-you, with a canned "thank you for contacting Interstellar Digital" message. Otherwise can be blank. This page will serve a re-direct after a web-to-lead form submission is submitted.

**Comment by neodigm** [comment]
This task is complete in v.01.

[Thank You Page](https://interstellarnick.github.io/interstellar-website/thank-you/)

**Comment by interstellarnick** [comment]
The thank-you page copy reads ....as soon as ASAP" which is redundent. Can we change to "as soon as possible."

**Comment by neodigm** [comment]
That would be redundantly redundant. The sentence above says "as soon as possible". Suggest one say "as soon as humanly possible" and the next sentence says "ASAP".

**Comment by neodigm** [comment]
This task is complete and will be visible in the next deployment.
