### ISSUE TITLE
Change train image to space image

### ISSUE THREAD

**Issue by interstellarnick** [interstellarnick/interstellar-website#17]
![AdobeStock_602014023](https://github.com/interstellarnick/interstellar-website/assets/140664594/1516295f-dccb-432a-9035-bc9f4fb9e1bb)
Image is attached to issue

**Comment by interstellarnick** [comment]
![AdobeStock_656405167 (1)](https://github.com/interstellarnick/interstellar-website/assets/140664594/f7c9add3-6e3e-4f2e-a7e9-a46bd5979c6e)
what about this?

**Comment by interstellarnick** [comment]
![Uploading AdobeStock_438343115.jpeg…]()

**Comment by neodigm** [comment]
This is done in v0.

**Comment by interstellarnick** [comment]
![Uploading AdobeStock_656519883.jpeg…]()
